apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{ name }}
  namespace: bidrag
  labels:
    team: bidrag
spec:
  azure:
    application:
      enabled: true
  secureLogs:
    enabled: true
  accessPolicy:
    inbound:
      rules:
      {{#each azure.inbound.rules}}
        - application: {{this.application}}
          namespace: {{this.namespace}}
          cluster: {{this.cluster}}
      {{/each}}
  webproxy: true
  image: {{ image }}
  liveness:
    path: /bidrag-dokument/actuator/health
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /bidrag-dokument/actuator/health
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /bidrag-dokument/actuator/prometheus
  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 512Mi
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  env:
  {{#each env}}
    - name: {{this.name}}
      value: "{{this.value}}"
  {{/each}}
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/{{ path }}/srvbidrag-dokument
        mountPath: /var/run/secrets/nais.io/srvbidrag-dokument
