name: bidrag-dokument
azure:
  inbound:
    rules:
      - application: bidrag-ui
        namespace: bidrag
        cluster: prod-fss
      - application: bidrag-dokument-arkivering
        namespace: bidrag
        cluster: prod-fss
      - application: bisys
        namespace: bidrag
        cluster: prod-fss
      - application: bidrag-arbeidsflyt
        namespace: bidrag
        cluster: prod-gcp
      - application: bidrag-dokument-bestilling
        namespace: bidrag
        cluster: prod-gcp
      - application: bidrag-reisekostnad-api
        namespace: bidrag
        cluster: prod-gcp
ingresses:
  - https://bidrag-dokument.nais.adeo.no/
  - https://bidrag-dokument.intern.nav.no/
  - https://bidrag-dokument.prod-fss.nais.io
  - https://bidrag-dokument.prod-fss-pub.nais.io
env:
    STS_ACCEPTED_AUDIENCE: srvbdarkivering,srvbisys
    BIDRAG_ARKIV_URL: https://bidrag-dokument-arkiv.nais.adeo.no/bidrag-dokument-arkiv
    BIDRAG_FORSENDELSE_URL: https://bidrag-dokument-forsendelse.intern.nav.no/api/forsendelse
    JOURNALPOST_URL: https://bidrag-dokument-journalpost.nais.adeo.no/bidrag-dokument-journalpost
    SECURITY_TOKEN_URL: https://security-token-service.nais.adeo.no/rest/v1/sts/token
    SRVBIDRAG_USERNAME: srvbidrag-dokument
    BIDRAG_DOKUMENT_JOURNALPOST_CLIENT_ID: prod-fss.bidrag.bidrag-dokument-journalpost
    BIDRAG_DOKUMENT_ARKIV_CLIENT_ID: prod-fss.bidrag.bidrag-dokument-arkiv
    BIDRAG_DOKUMENT_FORSENDELSE_CLIENT_ID: prod-gcp.bidrag.bidrag-dokument-forsendelse
    STS_ISSUER_URL: https://security-token-service.nais.adeo.no
    JAVA_OPTS: -Xmx1500m
    FORSENDELSE_ENABLED: false
path: prod
