name: bidrag-dokument
azure:
  inbound:
    rules:
      - application: bidrag-ui
        namespace: bidrag
        cluster: prod-fss
      - application: bidrag-dokument-arkivering
        namespace: bidrag
        cluster: prod-fss
      - application: bisys
        namespace: bidrag
        cluster: prod-fss
      - application: bidrag-arbeidsflyt
        namespace: bidrag
        cluster: prod-gcp
      - application: bidrag-dokument-bestilling
        namespace: bidrag
        cluster: prod-gcp
      - application: bidrag-reisekostnad-api
        namespace: bidrag
        cluster: prod-gcp
ingresses:
  - https://bidrag-dokument.nais.adeo.no/
  - https://bidrag-dokument.prod-fss.nais.io
  - https://bidrag-dokument.prod-fss-pub.nais.io
env:
  - name: STS_ACCEPTED_AUDIENCE
    value: srvbdarkivering,srvbisys
  - name: BIDRAG_ARKIV_URL
    value: https://bidrag-dokument-arkiv.nais.adeo.no/bidrag-dokument-arkiv
  - name: JOURNALPOST_URL
    value: https://bidrag-dokument-journalpost.nais.adeo.no/bidrag-dokument-journalpost
  - name: SECURITY_TOKEN_URL
    value: https://security-token-service.nais.adeo.no/rest/v1/sts/token
  - name: SRVBIDRAG_USERNAME
    value: srvbidrag-dokument
  - name: BIDRAG_DOKUMENT_JOURNALPOST_CLIENT_ID
    value: prod-fss.bidrag.bidrag-dokument-journalpost
  - name: BIDRAG_DOKUMENT_ARKIV_CLIENT_ID
    value: prod-fss.bidrag.bidrag-dokument-arkiv
  - name: STS_ISSUER_URL
    value: https://security-token-service.nais.adeo.no
  - name: JAVA_OPTS
    value: -Xmx1500m
path: prod
