name: bidrag-dokument
deploy: prod
port: 8080
ingresses:
  - https://bidrag-dokument.intern.nav.no/
  - https://bidrag-dokument.nais.adeo.no/
  - https://bidrag-dokument.prod-fss.nais.io
  - https://bidrag-dokument.prod-fss-pub.nais.io
env:
  - name: ACCEPTED_AUDIENCE
    value: bisys-p,bidrag-ui-p,bidrag-dokument-ui-p
  - name: BIDRAG_ARKIV_URL
    value: https://bidrag-dokument-arkiv.nais.adeo.no/bidrag-dokument-arkiv
  - name: ISSO_ISSUER_URL
    value: https://isso.adeo.no:443/isso/oauth2
  - name: JOURNALPOST_URL
    value: https://bidrag-dokument-journalpost.nais.adeo.no/bidrag-dokument-journalpost
  - name: SECURITY_TOKEN_URL
    value: https://security-token-service.nais.adeo.no/rest/v1/sts/token
  - name: SRVBIDRAG_USERNAME
    value: srvbidrag-dokument
